### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [khaiminh423/killedbygoogle#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by khaiminh423** [comment]
This is just one time project, basically replicating a website. I don't plan to maintain it anymore, i probably should archive this repo.
Anyway i add the license.

**Comment by khaiminh423** [comment]
added
